# These are supported funding model platforms

github: [Randi356, TeamYukki, TeamKillerX]
custom: ['https://t.me/RendyProjects', 'https://t.me/KillerXSupport','https://teamkillerx.gitbook.io/teamkillerx/']
